### ISSUE TITLE
Support non-avr processors

### ISSUE THREAD

**Issue by jscrane** [jscrane/TTS#11]
DAC on ESP32 (use dacWrite)
PWM on ESP8266

**Comment by cooleyandy** [comment]
Hi,
Does the code work for ESP8266 as it is currently?

I tried to compile and run on an ESP8266 nodemcu (2.4.0 library), using GPIO 3, along with a simple transistor amplifier. I seem to only get random tones coming from the speaker.

**Comment by jscrane** [comment]
That was the intention but I haven't been able to make it work with ESP8266 yet.

The ESP32 1-bit DAC is better but still not as good as the AVR.

Hopefully I will have some time to look at this over the summer.

**Comment by jscrane** [comment]
OK ESP8266 should work now. I've tested it with a Wemos Mini D1.
