### ISSUE TITLE
Does not work withesp8266, tried it with the node mcu and the wemos d1 mini. Produces no sound on the output

### ISSUE THREAD

**Issue by Kamalakkannan35** [jscrane/TTS#21]

**Comment by ESPboy-edu** [comment]
EPS8266 does not have DAC only [software sigma-delta ](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/sigma_delta.h)
try this my ESP8266 improved fork
https://github.com/ESPboy-edu/ESPboy-TTS

**Comment by jscrane** [comment]
I have just tested this with a Wemos D1 Mini and it works fine. @Kamalakkannan35 you must have made a mistake wiring it up.

`// Media pins
#define PWM D2
`

**Comment by jscrane** [comment]
@ESPboy-edu Arduino ESP8266 has PWM in software, see [here](https://arduino-esp8266.readthedocs.io/en/latest/reference.html#analog-output).
