### ISSUE TITLE
EXPLANATION REQUIRED

### ISSUE THREAD

**Issue by studentIITBombay** [jscrane/TTS#7]
Respected Sir
     
      I am trying to learn learn how to create text to speech library as part of my course curriculum.can you please explain the code you have provided as it is immensely difficult to understand it without any help.I shall be highly obliged to you.

Thank you

**Comment by jscrane** [comment]
Get started by understanding the principles involved; wikipedia is quite good: https://en.wikipedia.org/wiki/Speech_synthesis

Then read the code bearing those principles in mind. At a very high level, what it does is:
- convert text to phonemes, textToPhonemes()
- output phonemes using PWM, sayPhonemes()

(Note I did not write this code. If you have specific queries, you will need to ask the original author.)
